
title: Marges
description: joli blog

# Rendering ----------------------------------------

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  # input: GFM
  # hard_wrap: true
highlighter: rouge
# lsi:         false
excerpt_separator: <!--more-->
# incremental: false

# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr


# Folders and formatting ---------------------------------

# source:
# destination:
# safe: true
# exclude: [Gemfile, Rakefile, readme.md]
include:
  - _pages
# keep_files: []
# permalink: /:categories/:title/

# Collections ----------------------------------------------

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" #pages, posts, drafts
    values:
      layout: "default"

collections:
  studies:
    output: true
    permalink: /:collection/:path/
    title: Dossiers