
title: Marges
description: joli blog
## prod conf
baseurl: /marges # the subpath of your site, e.g. /blog
url: https://clairezed.github.io # the base hostname & protocol for your site

markdown: kramdown
timezone: Europe/Paris
encoding: utf-8
locale: fr


sass:
  sass_dir: _sass
  style: compressed

# source:
# destination:
# safe: true
# exclude: [Gemfile, Rakefile, readme.md]
include:
  - _pages
# keep_files: []
# permalink: /:categories/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" #pages, posts, drafts
    values:
      layout: "default"

collections:
  studies:
    output: true
    permalink: /:collection/:path/
    title: Dossiers